### ISSUE TITLE
Any accounts registered are not stored.

### ISSUE THREAD

**Issue by HenryHatten** [lnu/NHibernateIdentity#1]
Any accounts registered are not saved in the database.

Logging off, re-running the app then trying to login again does not work.

Also you should put back in the database file you took out or things won't run.

**Comment by lnu** [comment]
Did you try the official repo https://github.com/nhibernate/NHibernate.AspNet.Identity?

**Comment by HenryHatten** [comment]
That's the one the sample uses is it not?

After further testing the problem appears to be that when you close visual studio and restart it, all user data entered into the DB gets lost. Functionality works fine with visual studio open. The same thing happens if you inspect the data within visual studio by double clicking on the mdf file. The data shows up, but in the next run all the data gets lost again. So it seems that closing the connection to the database in visual studio results in the data getting lost.

**Comment by lnu** [comment]
In the sample, the database content is dropped/created at each start of the pool.
https://github.com/lnu/NHibernateIdentity/blob/master/NHibernateIdentity/NHibernateSessionFactory.cs#L47
Remove the lines 47-48-49 and it should work.

**Comment by HenryHatten** [comment]
Yes that works fine, thanks!

**Comment by HenryHatten** [comment]
For anyone who wants to update the packages used in the sample, make sure to **not** overwrite _UnityConfig.cs_ when prompted when updating the Unity.Mvc package.
